### ISSUE TITLE
Setting apk directory is overwritten by automatic discovery

### ISSUE THREAD

**Issue by runningcode** [runningcode/fladle#19]

**Comment by winterDroid** [comment]
Probably this causes also 
```
Caused by: kotlin.KotlinNullPointerException
        at com.osacky.flank.gradle.FlankGradlePlugin.findDebugAndInstrumentationApk(FlankGradlePlugin.kt:95)
        at com.osacky.flank.gradle.FlankGradlePlugin.access$findDebugAndInstrumentationApk(FlankGradlePlugin.kt:12)
        at com.osacky.flank.gradle.FlankGradlePlugin$configureTasks$1.execute(FlankGradlePlugin.kt:30)
        at com.osacky.flank.gradle.FlankGradlePlugin$configureTasks$1.execute(FlankGradlePlugin.kt:12)
        at org.gradle.api.internal.plugins.DefaultPluginManager$3.execute(DefaultPluginManager.java:240)
        at org.gradle.api.internal.plugins.DefaultPluginManager$3.execute(DefaultPluginManager.java:238)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
        at org.gradle.api.internal.plugins.DefaultPluginManager.withPlugin(DefaultPluginManager.java:243)
        at com.osacky.flank.gradle.FlankGradlePlugin.configureTasks(FlankGradlePlugin.kt:28)
        at com.osacky.flank.gradle.FlankGradlePlugin.apply(FlankGradlePlugin.kt:17)
        at com.osacky.flank.gradle.FlankGradlePlugin.apply(FlankGradlePlugin.kt:12)
```

Maybe this should happen after evaluation?
