### ISSUE TITLE
Using the output of a Gradle task to set the value of a property on `FlankGradleExtension`

### ISSUE THREAD

**Issue by jschear** [runningcode/fladle#239]
I'm trying to set the value of the `testTargets` property using the ouput of a task. It looks like the `testTargets` property is getting resolved at configuration time, leading to a `java.io.FileNotFoundException` (it tries to read a file that would be generated by the task).

Is this a bug, or something that isn't generally supported?

### Context

One feature we’ve implemented in our current non-fladle flank setup is a “stability gate” for new and changed tests — we use `git diff` to generate a list of test classes that have been modified or added in a pull request, and then dynamically generate a flank yml config that runs those tests a large number of times to check if any flakiness was introduced.

I’m trying to implement this functionality when using fladle. My first thought was to wrap the git invocation in a gradle task, and wire up an output property from the task to the `testTargets` property in the fladle extension:

```kotlin
// In app/build.gradle.kts

open class GetChangedTestTargets : DefaultTask() {
  @OutputFile
  val outputFile: RegularFileProperty = project.objects.fileProperty()

  @TaskAction
  fun action() {
    // TODO(fladle): execute a git diff between the current branch and master to calculate which test targets should run.
    outputFile.asFile.get().writeText(
      """
      class foo.bar.SomeTestClass1
      class foo.bar.SomeTestClass2
      """.trimIndent()
    )
  }
}

val stabilityGateTestTargets by tasks.registering(GetChangedTestTargets::class) {
  // This task should never be considered up to date because it depends on state outside of the build: it invokes git.
  outputs.upToDateWhen { false }
  outputFile.set(layout.buildDirectory.file("stabilityGateTestTargets.txt"))
}

fladle {
  configs {
    // ...
    create("stabilityGateTests") {
      // ...
      testTargets.set(stabilityGateTestTargets.map { it.outputFile.get().asFile.readLines() })
    }
  }
}
```

… but unfortunately it appears that the testTargets is getting resolved at configuration time, because I get:
```
A problem occurred configuring project ':app'.
> java.io.FileNotFoundException: /Users/jschear/dev/myproject/app/build/stabilityGateTestTargets.txt (No such file or directory)
```

Looking at the stacktrace, it looks like the `validateOptionsUsed` function is the culprit.
```
Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: /Users/jschear/dev/myproject/app/build/stabilityGateTestTargets.txt (No such file or directory)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:61)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.api.internal.provider.AbstractProperty.calculatePresence(AbstractProperty.java:63)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.isPresent(AbstractMinimalProvider.java:74)
        at com.osacky.flank.gradle.FladleConfig$DefaultImpls.getPresentProperties(FladleConfig.kt:462)
        at com.osacky.flank.gradle.FladleConfigImpl.getPresentProperties(FladleConfigImpl.kt:9)
        at com.osacky.flank.gradle.validation.ValidateOptionsKt.validateOptionsUsed(ValidateOptions.kt:8)
        at com.osacky.flank.gradle.FladlePluginDelegate.createTasksForConfig(FladlePluginDelegate.kt:72)
        at com.osacky.flank.gradle.FladlePluginDelegate.access$createTasksForConfig(FladlePluginDelegate.kt:15)
        at com.osacky.flank.gradle.FladlePluginDelegate$configureTasks$1.execute(FladlePluginDelegate.kt:64)
        at com.osacky.flank.gradle.FladlePluginDelegate$configureTasks$1.execute(FladlePluginDelegate.kt:15)
```

**Comment by runningcode** [comment]
Hmm, i'll need to think about this more. Pulling the validation actions out in to the task execution phase could lead confusing error messages. Perhaps I can add a flag to disable the validation though, would that work?

**Comment by jschear** [comment]
Conditionally disabling validation would work for me. 👍 

Just curious -- what sort of confusing error messages are you imagining? I feel like getting error messages from the `execFlank...` tasks (or from separate `validate...FlankConfig` tasks) would be reasonable.

**Comment by runningcode** [comment]
@jschear nvm, I was reading the failing tests incorrectly. It looks like this PR should do the trick: https://github.com/runningcode/fladle/pull/244

**Comment by runningcode** [comment]
@jschear could you test a snapshot and let me know if it fixes the issue for you? https://runningcode.github.io/fladle/snapshots/

**Comment by jschear** [comment]
I was able to try it out via an `includeBuild` and it works great -- thank you!

I had trouble consuming the snapshot, though:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'slack-android-ng'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.osacky.flank.gradle:fladle:0.15.1-SNAPSHOT.
     Required by:
         project :
      > No matching variant of com.osacky.flank.gradle:fladle:0.15.1-SNAPSHOT:20210405.222926-5 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
          - Variant 'apiElements' capability com.osacky.flank.gradle:fladle:0.15.1-SNAPSHOT declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
          - Variant 'runtimeElements' capability com.osacky.flank.gradle:fladle:0.15.1-SNAPSHOT declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```
I saw [the same issue](https://github.com/JetBrains/markdown/issues/70) recently on a different library -- it seems like you might need to declare Java 8 compatibility somewhere? (I'm not sure if this is an issue on my end or with the snapshot. 😅 )
