### ISSUE TITLE
Fladle 0.17.0 broke configuration cache

### ISSUE THREAD

**Issue by jasonschroeder-sfdc** [runningcode/fladle#278]
Partial stacktrace:

```
Cannot obtain value from provider of Gradle property 'com.osacky.fladle.enableTestUploads' at configuration time.
Use a provider returned by 'forUseAtConfigurationTime()' instead.
java.lang.IllegalStateException: Cannot obtain value from provider of Gradle property 'com.osacky.fladle.enableTestUploads' at configuration time.
Use a provider returned by 'forUseAtConfigurationTime()' instead.
        at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$NonConfigurationTimeProvider.vetoAtConfigurationTime(DefaultValueSourceProviderFactory.java:198)
        at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$ValueSourceProvider.calculateOwnValue(DefaultValueSourceProviderFactory.java:298)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrElse(AbstractMinimalProvider.java:98)
        at com.osacky.flank.gradle.ImportReportDelegateKt.importReport(ImportReportDelegate.kt:18)
        at com.osacky.flank.gradle.FladlePluginDelegate.createTasksForConfig(FladlePluginDelegate.kt:146)
        at com.osacky.flank.gradle.FladlePluginDelegate.access$createTasksForConfig(FladlePluginDelegate.kt:17)
        at com.osacky.flank.gradle.FladlePluginDelegate$configureTasks$1.execute(FladlePluginDelegate.kt:65)
        at com.osacky.flank.gradle.FladlePluginDelegate$configureTasks$1.execute(FladlePluginDelegate.kt:17)
```

**Comment by jasonschroeder-sfdc** [comment]
Introduced in https://github.com/runningcode/fladle/pull/277/
