### ISSUE TITLE
Automatic APK detection not working

### ISSUE THREAD

**Issue by winterDroid** [runningcode/fladle#35]
Unfortunately the APK detection is not working for me. I have a simple sample project with AGP 3.3.0 and Gradle 4.10.1. Once fladle tries to derive the APK automatically it fails with: `Could not find AppExtension in app`

Here is the stacktrace:
```
Caused by: java.lang.IllegalArgumentException: Could not find AppExtension in app
        at com.osacky.flank.gradle.FlankGradlePlugin.findDebugAndInstrumentationApk(FlankGradlePlugin.kt:97)
        at com.osacky.flank.gradle.FlankGradlePlugin.access$findDebugAndInstrumentationApk(FlankGradlePlugin.kt:13)
        at com.osacky.flank.gradle.FlankGradlePlugin$configureTasks$2$1.execute(FlankGradlePlugin.kt:43)
        at com.osacky.flank.gradle.FlankGradlePlugin$configureTasks$2$1.execute(FlankGradlePlugin.kt:13)
        at org.gradle.api.internal.plugins.DefaultPluginManager$3.execute(DefaultPluginManager.java:240)
        at org.gradle.api.internal.plugins.DefaultPluginManager$3.execute(DefaultPluginManager.java:238)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
        at org.gradle.api.internal.plugins.DefaultPluginManager.withPlugin(DefaultPluginManager.java:243)
        at com.osacky.flank.gradle.FlankGradlePlugin$configureTasks$2.execute(FlankGradlePlugin.kt:41)
```

I tried applying the Android plugin before and after applying fladle. But nothing worked.

**Comment by runningcode** [comment]
Maybe we can copy the code from here: https://github.com/trevjonez/composer-gradle-plugin/blob/master/plugin/src/main/kotlin/com/trevjonez/composer/internal/ComposerApplicationPlugin.kt
