### ISSUE TITLE
ImportJUnitXmlReports task has been deprecated in favor of ImportJUnitXmlReports

### ISSUE THREAD

**Issue by kozaxinan** [runningcode/fladle#384]
Since the new version of develocity plugin, we started get this log in builds. 

```
> Configure project :
The 'com.gradle.enterprise.gradleplugin.test.ImportJUnitXmlReports' task has been deprecated in favor of 'com.gradle.develocity.agent.gradle.test.ImportJUnitXmlReports'. Please update all references to this class and to the 'com.gradle.enterprise.gradleplugin.test.JUnitXmlDialect' in your build logic.
com.gradle.develocity.DevelocityException: The 'com.gradle.enterprise.gradleplugin.test.ImportJUnitXmlReports' task has been deprecated in favor of 'com.gradle.develocity.agent.gradle.test.ImportJUnitXmlReports'. Please update all references to this class and to the 'com.gradle.enterprise.gradleplugin.test.JUnitXmlDialect' in your build logic.
	at com.gradle.enterprise.gradleplugin.test.ImportJUnitXmlReports.register(SourceFile:113)
	at com.osacky.flank.gradle.ImportReportDelegateKt.importReport(ImportReportDelegate.kt:24)
	at com.osacky.flank.gradle.FladlePluginDelegate.createTasksForConfig(FladlePluginDelegate.kt:145)
	at com.osacky.flank.gradle.FladlePluginDelegate.access$createTasksForConfig(FladlePluginDelegate.kt:16)
	at com.osacky.flank.gradle.FladlePluginDelegate$configureTasks$1.execute(FladlePluginDelegate.kt:64)
	at com.osacky.flank.gradle.FladlePluginDelegate$configureTasks$1.execute(FladlePluginDelegate.kt:16)
	at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:122)
```

**Comment by ritesh-singh** [comment]
Our CI logs and build scans are filled with these logs.

Would appreciate and update on this issue or if there's a way to disable the logs.
