### ISSUE TITLE
Updating matrix file failed

### ISSUE THREAD

**Issue by arohim** [runningcode/fladle#85]
Hi, this is my first time using fladle plugin, the running script seems fine until FetchArtifacts tasks on **Windows OS**, on CI system(Ubuntu) is works very well, the result on Firebase Test lab is totally fine too.

**Running script**
`**./gradlew assembleMock assembleAndroidTest runFlank**`

**my configurations** 
```
**
fladle {
    serviceAccountCredentials("${project.file("src/release/app-dist-account.json")}")
    projectId("dev-test")
    useOrchestrator = true

    debugApk("$buildDir/outputs/apk/mock/app-mock.apk")

    instrumentationApk("$buildDir/outputs/apk/androidTest/mock/app-mock-androidTest.apk")

    devices = [
            ["model": "Nexus6", "version": "21", "locale": "en", "orientation": "portrait"]
    ]
}**
```

Gradle output
```
9:35:22 AM: Executing task 'runFlank'...

Executing tasks: [runFlank] in project C:\Users\Him\Documents\androids\7peaksandroiddevelopertest

> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestKotlin NO-SOURCE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validateTaskProperties UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
> Task :app:writeConfigProps

> Task :app:execFlank
AndroidArgs
    gcloud:
      results-bucket: test-lab-hfx53fsx452xq-y2af9whtjinwi
      results-dir: null
      record-video: true
      timeout: 15m
      async: false
      results-history-name: null
      # Android gcloud
      app: C:\Users\Him\Documents\androids\7peaksandroiddevelopertest\app\build\outputs\apk\mock\app-mock.apk
      test: C:\Users\Him\Documents\androids\7peaksandroiddevelopertest\app\build\outputs\apk\androidTest\mock\app-mock-androidTest.apk
      auto-google-login: false
      use-orchestrator: true
      directories-to-pull:

      performance-metrics: true
      test-runner-class: null
      test-targets:

      device:
        - model: Nexus6
          version: 21
          locale: en
          orientation: portrait
      num-flaky-test-attempts: 0

    flank:
      max-test-shards: 1
      shard-time: -1
      num-test-runs: 1
      smart-flank-gcs-path: 
      smart-flank-disable-upload: false
      files-to-download:

      test-targets-always-run:

      disable-sharding: false
      project: peaks-dev-test
      local-result-dir: results
      # Android Flank Yml
      keep-file-path: false
      additional-app-test-apks:

RunTests
  Uploading app-mock-androidTest.apk   Uploading app-mock.apk ..


  Smart Flank cache hit: 0% (0 / 4)
  Shard times: 40s

  4 tests / 1 shard

  1 matrix ids created in 0m 5s
  https://console.developers.google.com/storage/browser/test-lab-hfx53fsx452xq-y2af9whtjinwi/2020-02-17_02-35-28.377000_StjU/

PollMatrices
  0m  1s matrix-9n8hgyh9qsf4a Nexus6-21 VALIDATING
  0m 13s matrix-9n8hgyh9qsf4a Nexus6-21 PENDING
  0m 32s matrix-9n8hgyh9qsf4a Nexus6-21 Starting attempt 1.
  0m 32s matrix-9n8hgyh9qsf4a Nexus6-21 RUNNING
  1m 28s matrix-9n8hgyh9qsf4a Nexus6-21 Started logcat recording.
  1m 28s matrix-9n8hgyh9qsf4a Nexus6-21 Preparing device.
  2m  0s matrix-9n8hgyh9qsf4a Nexus6-21 Installing apps.
  2m 19s matrix-9n8hgyh9qsf4a Nexus6-21 Retrieving Pre-Test Package Stats information from the device.
  2m 19s matrix-9n8hgyh9qsf4a Nexus6-21 Retrieving Performance Environment information from the device.
  2m 19s matrix-9n8hgyh9qsf4a Nexus6-21 Started crash detection.
  2m 19s matrix-9n8hgyh9qsf4a Nexus6-21 Started crash monitoring.
  2m 19s matrix-9n8hgyh9qsf4a Nexus6-21 Started performance monitoring.
  2m 25s matrix-9n8hgyh9qsf4a Nexus6-21 Started video recording.
  2m 25s matrix-9n8hgyh9qsf4a Nexus6-21 Starting instrumentation test.
  3m 27s matrix-9n8hgyh9qsf4a Nexus6-21 Completed instrumentation test.
  3m 33s matrix-9n8hgyh9qsf4a Nexus6-21 Stopped performance monitoring.
  4m  5s matrix-9n8hgyh9qsf4a Nexus6-21 Stopped crash monitoring.
  4m  5s matrix-9n8hgyh9qsf4a Nexus6-21 Retrieving Post-test Package Stats information from the device.
  4m  5s matrix-9n8hgyh9qsf4a Nexus6-21 Stopped logcat recording.
  4m  5s matrix-9n8hgyh9qsf4a Nexus6-21 Done. Test time = 57 (secs)
  4m  5s matrix-9n8hgyh9qsf4a Nexus6-21 Starting results processing. Attempt: 1
  4m 15s matrix-9n8hgyh9qsf4a Nexus6-21 Completed results processing. Time taken = 5 (secs)
  4m 15s matrix-9n8hgyh9qsf4a Nexus6-21 FINISHED
  4m 15s matrix-9n8hgyh9qsf4a FINISHED

FetchArtifacts
  .
  Updating matrix file

java.lang.NullPointerException
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:247)
	at java.nio.file.Paths.get(Paths.java:84)
	at ftl.reports.util.ReportManager.getWebLink(ReportManager.kt:44)
	at ftl.reports.util.ReportManager.processXml(ReportManager.kt:68)
	at ftl.reports.util.ReportManager.parseTestSuite(ReportManager.kt:89)
	at ftl.reports.util.ReportManager.generate(ReportManager.kt:95)
	at ftl.run.TestRunner.newRun(TestRunner.kt:349)
	at ftl.run.TestRunner$newRun$1.invokeSuspend(TestRunner.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:45)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterCompletionInternal(Scopes.kt:32)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:310)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:236)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:849)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:811)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:787)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at ftl.cli.firebase.test.android.AndroidRunCommand.run(AndroidRunCommand.kt:49)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1729)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
	at picocli.CommandLine.execute(CommandLine.java:1864)
	at ftl.Main$Companion.main(Main.kt:41)
	at ftl.Main.main(Main.kt)

> Task :app:execFlank FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:execFlank'.
> Process 'command 'C:\Program Files\Android\Android Studio\jre\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 59s
2 actionable tasks: 2 executed
9:42:22 AM: Task execution finished 'runFlank'.

```

**Comment by ynsok** [comment]
the same, any idea how to solve it ?

**Comment by runningcode** [comment]
Hi, thanks for filing. This is a bug in flank, not fladle. https://github.com/Flank/flank/issues/628
Please thumbs up the issue there so that it can be address!
